{% set name = "hilltop-py" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hilltop-py-{{ version }}.tar.gz
  sha256: 54f3ea805b2d140f2353d7d4a1f6bafdfbee401c9bebd1ff433547d4b4c94277

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pandas
    - pydantic
    - orjson
    - requests

test:
  imports:
    - hilltoppy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mullenkamp/hilltop-py
  summary: Functions to access Hilltop data
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mullenkamp
