{% set name = "hilltop-py" %}
{% set package_name = "hilltop_py" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: f42ba221aff31f1b6b728a2686e4a0485c50ac4311921388e4e1c3aff532b8d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - pandas
    - pydantic <2
    - orjson
    - requests

test:
  imports:
    - hilltoppy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mullenkamp/hilltop-py
  summary: Tools to access Hilltop data
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mullenkamp
