{% set name = "hilltop-py" %}
{% set version = "2.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hilltop-py-{{ version }}.tar.gz
  sha256: 78009a343ed3ef202dcac9221fcfa56ba4218702f9f0e9b7a78b92b4e3f2632d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pandas
    - pydantic >2
    - orjson
    - requests

test:
  imports:
    - hilltoppy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mullenkamp/hilltop-py
  summary: Functions to access Hilltop data
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mullenkamp
